name: Deploy BigQuery Stored Procedures

on:
  workflow_dispatch:

jobs:
  deploy-procedures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set GCP Project ID
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: List all files for debugging
        run: find "${{ github.workspace }}" -name "*.sql" 

      - name: Deploy Stored Procedures to BigQuery
        run: |
          find "${{ github.workspace }}/tests" -name "*.sql" | while read sql_script; do
            bq query --use_legacy_sql=false < "$sql_script"
          done
